/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AwardContract__factory } from "./AwardContract__factory";
export { DSOMW__factory } from "./DSOMW__factory";
export { DonationAndVotingSystemContract__factory } from "./DonationAndVotingSystemContract__factory";
export { GoldContract__factory } from "./GoldContract__factory";
export { MyERC20__factory } from "./MyERC20__factory";
export { MyERC721__factory } from "./MyERC721__factory";
export { StringHelper__factory } from "./StringHelper__factory";
