/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface DonationAndVotingSystemContractInterface
  extends utils.Interface {
  functions: {
    "addNewDonation(string,uint256,uint256)": FunctionFragment;
    "awards()": FunctionFragment;
    "getAward()": FunctionFragment;
    "getDonationIds()": FunctionFragment;
    "getDonationInfo(uint256,uint256)": FunctionFragment;
    "getDonationStatus(uint256,uint256)": FunctionFragment;
    "getDonationStatus(uint256)": FunctionFragment;
    "getDonationVotesInfo(uint256,uint256)": FunctionFragment;
    "getGoldConsumeByDonation()": FunctionFragment;
    "getGoldConsumedByVote()": FunctionFragment;
    "getGoldRewardFromDonationApproved(uint256)": FunctionFragment;
    "getMaxVotingTimes()": FunctionFragment;
    "getUserAddresses()": FunctionFragment;
    "getUserDonationIds()": FunctionFragment;
    "getUserVotesInfo()": FunctionFragment;
    "getWhetherUserCanGetAwardReward(uint256)": FunctionFragment;
    "getWhetherUserCanGetGoldReward(uint256,uint256)": FunctionFragment;
    "gold()": FunctionFragment;
    "voteOnDonation(uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addNewDonation"
      | "awards"
      | "getAward"
      | "getDonationIds"
      | "getDonationInfo"
      | "getDonationStatus(uint256,uint256)"
      | "getDonationStatus(uint256)"
      | "getDonationVotesInfo"
      | "getGoldConsumeByDonation"
      | "getGoldConsumedByVote"
      | "getGoldRewardFromDonationApproved"
      | "getMaxVotingTimes"
      | "getUserAddresses"
      | "getUserDonationIds"
      | "getUserVotesInfo"
      | "getWhetherUserCanGetAwardReward"
      | "getWhetherUserCanGetGoldReward"
      | "gold"
      | "voteOnDonation"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addNewDonation",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "awards", values?: undefined): string;
  encodeFunctionData(functionFragment: "getAward", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getDonationIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDonationInfo",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getDonationStatus(uint256,uint256)",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getDonationStatus(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getDonationVotesInfo",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getGoldConsumeByDonation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGoldConsumedByVote",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGoldRewardFromDonationApproved",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMaxVotingTimes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserDonationIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserVotesInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWhetherUserCanGetAwardReward",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getWhetherUserCanGetGoldReward",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "gold", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "voteOnDonation",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "addNewDonation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "awards", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAward", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDonationIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDonationInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDonationStatus(uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDonationStatus(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDonationVotesInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGoldConsumeByDonation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGoldConsumedByVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGoldRewardFromDonationApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaxVotingTimes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserDonationIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserVotesInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWhetherUserCanGetAwardReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWhetherUserCanGetGoldReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gold", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voteOnDonation",
    data: BytesLike
  ): Result;

  events: {};
}

export interface DonationAndVotingSystemContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DonationAndVotingSystemContractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addNewDonation(
      content: PromiseOrValue<string>,
      start_time: PromiseOrValue<BigNumberish>,
      end_time: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    awards(overrides?: CallOverrides): Promise<[string]>;

    getAward(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getDonationIds(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    getDonationInfo(
      id: PromiseOrValue<BigNumberish>,
      time_now: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber, BigNumber, BigNumber]>;

    "getDonationStatus(uint256,uint256)"(
      id: PromiseOrValue<BigNumberish>,
      time_now: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    "getDonationStatus(uint256)"(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getDonationVotesInfo(
      id: PromiseOrValue<BigNumberish>,
      time_now: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[], BigNumber[], string[]]>;

    getGoldConsumeByDonation(overrides?: CallOverrides): Promise<[BigNumber]>;

    getGoldConsumedByVote(overrides?: CallOverrides): Promise<[BigNumber]>;

    getGoldRewardFromDonationApproved(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getMaxVotingTimes(overrides?: CallOverrides): Promise<[BigNumber]>;

    getUserAddresses(overrides?: CallOverrides): Promise<[string[]]>;

    getUserDonationIds(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    getUserVotesInfo(
      overrides?: CallOverrides
    ): Promise<[BigNumber[], BigNumber[], BigNumber[]]>;

    getWhetherUserCanGetAwardReward(
      time_now: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getWhetherUserCanGetGoldReward(
      id: PromiseOrValue<BigNumberish>,
      time_now: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    gold(overrides?: CallOverrides): Promise<[string]>;

    voteOnDonation(
      user_vote: PromiseOrValue<BigNumberish>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addNewDonation(
    content: PromiseOrValue<string>,
    start_time: PromiseOrValue<BigNumberish>,
    end_time: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  awards(overrides?: CallOverrides): Promise<string>;

  getAward(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getDonationIds(overrides?: CallOverrides): Promise<BigNumber[]>;

  getDonationInfo(
    id: PromiseOrValue<BigNumberish>,
    time_now: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string, string, BigNumber, BigNumber, BigNumber]>;

  "getDonationStatus(uint256,uint256)"(
    id: PromiseOrValue<BigNumberish>,
    time_now: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number>;

  "getDonationStatus(uint256)"(
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number>;

  getDonationVotesInfo(
    id: PromiseOrValue<BigNumberish>,
    time_now: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber[], BigNumber[], string[]]>;

  getGoldConsumeByDonation(overrides?: CallOverrides): Promise<BigNumber>;

  getGoldConsumedByVote(overrides?: CallOverrides): Promise<BigNumber>;

  getGoldRewardFromDonationApproved(
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getMaxVotingTimes(overrides?: CallOverrides): Promise<BigNumber>;

  getUserAddresses(overrides?: CallOverrides): Promise<string[]>;

  getUserDonationIds(overrides?: CallOverrides): Promise<BigNumber[]>;

  getUserVotesInfo(
    overrides?: CallOverrides
  ): Promise<[BigNumber[], BigNumber[], BigNumber[]]>;

  getWhetherUserCanGetAwardReward(
    time_now: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getWhetherUserCanGetGoldReward(
    id: PromiseOrValue<BigNumberish>,
    time_now: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  gold(overrides?: CallOverrides): Promise<string>;

  voteOnDonation(
    user_vote: PromiseOrValue<BigNumberish>,
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addNewDonation(
      content: PromiseOrValue<string>,
      start_time: PromiseOrValue<BigNumberish>,
      end_time: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    awards(overrides?: CallOverrides): Promise<string>;

    getAward(overrides?: CallOverrides): Promise<void>;

    getDonationIds(overrides?: CallOverrides): Promise<BigNumber[]>;

    getDonationInfo(
      id: PromiseOrValue<BigNumberish>,
      time_now: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber, BigNumber, BigNumber]>;

    "getDonationStatus(uint256,uint256)"(
      id: PromiseOrValue<BigNumberish>,
      time_now: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number>;

    "getDonationStatus(uint256)"(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number>;

    getDonationVotesInfo(
      id: PromiseOrValue<BigNumberish>,
      time_now: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[], BigNumber[], string[]]>;

    getGoldConsumeByDonation(overrides?: CallOverrides): Promise<BigNumber>;

    getGoldConsumedByVote(overrides?: CallOverrides): Promise<BigNumber>;

    getGoldRewardFromDonationApproved(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getMaxVotingTimes(overrides?: CallOverrides): Promise<BigNumber>;

    getUserAddresses(overrides?: CallOverrides): Promise<string[]>;

    getUserDonationIds(overrides?: CallOverrides): Promise<BigNumber[]>;

    getUserVotesInfo(
      overrides?: CallOverrides
    ): Promise<[BigNumber[], BigNumber[], BigNumber[]]>;

    getWhetherUserCanGetAwardReward(
      time_now: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getWhetherUserCanGetGoldReward(
      id: PromiseOrValue<BigNumberish>,
      time_now: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    gold(overrides?: CallOverrides): Promise<string>;

    voteOnDonation(
      user_vote: PromiseOrValue<BigNumberish>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    addNewDonation(
      content: PromiseOrValue<string>,
      start_time: PromiseOrValue<BigNumberish>,
      end_time: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    awards(overrides?: CallOverrides): Promise<BigNumber>;

    getAward(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getDonationIds(overrides?: CallOverrides): Promise<BigNumber>;

    getDonationInfo(
      id: PromiseOrValue<BigNumberish>,
      time_now: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getDonationStatus(uint256,uint256)"(
      id: PromiseOrValue<BigNumberish>,
      time_now: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getDonationStatus(uint256)"(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDonationVotesInfo(
      id: PromiseOrValue<BigNumberish>,
      time_now: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGoldConsumeByDonation(overrides?: CallOverrides): Promise<BigNumber>;

    getGoldConsumedByVote(overrides?: CallOverrides): Promise<BigNumber>;

    getGoldRewardFromDonationApproved(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getMaxVotingTimes(overrides?: CallOverrides): Promise<BigNumber>;

    getUserAddresses(overrides?: CallOverrides): Promise<BigNumber>;

    getUserDonationIds(overrides?: CallOverrides): Promise<BigNumber>;

    getUserVotesInfo(overrides?: CallOverrides): Promise<BigNumber>;

    getWhetherUserCanGetAwardReward(
      time_now: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWhetherUserCanGetGoldReward(
      id: PromiseOrValue<BigNumberish>,
      time_now: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gold(overrides?: CallOverrides): Promise<BigNumber>;

    voteOnDonation(
      user_vote: PromiseOrValue<BigNumberish>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addNewDonation(
      content: PromiseOrValue<string>,
      start_time: PromiseOrValue<BigNumberish>,
      end_time: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    awards(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAward(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getDonationIds(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDonationInfo(
      id: PromiseOrValue<BigNumberish>,
      time_now: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getDonationStatus(uint256,uint256)"(
      id: PromiseOrValue<BigNumberish>,
      time_now: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getDonationStatus(uint256)"(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDonationVotesInfo(
      id: PromiseOrValue<BigNumberish>,
      time_now: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGoldConsumeByDonation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGoldConsumedByVote(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGoldRewardFromDonationApproved(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getMaxVotingTimes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getUserAddresses(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getUserDonationIds(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserVotesInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getWhetherUserCanGetAwardReward(
      time_now: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWhetherUserCanGetGoldReward(
      id: PromiseOrValue<BigNumberish>,
      time_now: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gold(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    voteOnDonation(
      user_vote: PromiseOrValue<BigNumberish>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
