/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AwardContract } from "./AwardContract";
export type { DonationAndVotingSystemContract } from "./DonationAndVotingSystemContract";
export type { GoldContract } from "./GoldContract";
export type { StringHelper } from "./StringHelper";
