/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AwardContract } from "./AwardContract";
export type { DSOMW } from "./DSOMW";
export type { DonationAndVotingSystemContract } from "./DonationAndVotingSystemContract";
export type { GoldContract } from "./GoldContract";
export type { MyERC20 } from "./MyERC20";
export type { MyERC721 } from "./MyERC721";
export type { StringHelper } from "./StringHelper";
